version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_qeq
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quem-e-quem
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
